# Overview
# Author: Erika Castañeda  
# Date: 10 Dec 2023
#
# This R script analyzes the statistics of a classification task.
# It processes classification results stored in a CSV file, checks for chromosome classifications,
# and generates visualizations using ggplot2. The script integrates data from MUMmer and HG38 reference genome
# to visualize classification statistics.

## Libraries Used
library(ggplot2)
library(dplyr)
library(readr)

## Data Input 
# 
# The data for this analysis originates from the output generated by MUMmer 4.0.0beta2,
# which maps a de novo assembled genome against the GRCh38 reference. The goal is to classify contigs 
# at the chromosome level using the latest human reference assembly.
#
# The CSV file contains the following columns:
# - X1: Chromosome (character)
# - X2: Contig (character)
# - X3: Start position (numeric)
# - X4: End position (numeric)

# Read classification results from CSV file
df <- read_table("/resum_classification.csv", col_names = FALSE) %>%
  rename(Chromosome = X1, Contig = X2, Start = X3, End = X4)

# Clean up 'names' column to match chromosome names
df$names <- sub(">", "", df$Chromosome)

## Reference Database
#
# Information of reference genome:
# - UCSC Genome Browser assembly ID: hg38
# - Assembly accession: GCA_000001405.29
# - NCBI Genome ID: 51 (Homo sapiens (human))
# - BioProject ID: PRJNA31257
#
# Chromosome naming conventions:
# - Haplotype chromosome names include the NCBI accession number (e.g., chr6_GL000256v2_alt).
# - Fix sequence names include "fix" (e.g., chr7_KQ031388v1_fix).
# - Unlocalized contig names include "random".
# - Unplaced contig names include "chrUn" followed by the NCBI accession number.

# Read HG38 chromosome information
hg38_chromAlias <- read_table("/names_hg38.txt")

# Clean up chromosome names
hg38_chromAlias$Chromosomes <- sub("_.*$", "", hg38_chromAlias$Sequence_name)

## Data Analysis
# Merge dataframes to include chromosome names in classification results
result <- merge(hg38_chromAlias, df, by = "names", all.y = TRUE)
result <- result[, c('Chromosomes', 'names', 'Contig', 'Start', 'End')]

# Check for unclassified chromosomes
vacios <- filter(result, is.na(Chromosomes))

## Data Transformation
# Fill in empty chromosome values based on known names
result <- mutate(result, Chromosomes = ifelse(names == "NC_000023.11", "chrX", Chromosomes))
result <- mutate(result, Chromosomes = ifelse(names == "NC_000024.10", "chrY", Chromosomes))

## Data Visualization
# Summarize data for visualization
resumen <- result %>%
  group_by(Chromosomes, Contig) %>%
  summarise(n = n()) %>%
  ungroup()

# Identify exclusive contigs (contigs appearing in only one chromosome)
contigs_exclusivos <- resumen %>%
  group_by(Contig) %>%
  filter(n_distinct(Chromosomes) == 1 & n() == 1) %>%
  ungroup() %>%
  mutate(es_exclusivo = TRUE)

resumen <- resumen %>%
  left_join(contigs_exclusivos %>%
              select(Contig, es_exclusivo), by = "Contig") %>%
  mutate(es_exclusivo = ifelse(is.na(es_exclusivo), FALSE, TRUE))

# Create barplot of unique/duplicate contigs
etiquetas_numericas <- resumen %>%
  group_by(Chromosomes, es_exclusivo) %>%
  summarise(num_contigs = sum(n)) 

ggplot(etiquetas_numericas, aes(x = Chromosomes, y = num_contigs, fill = factor(es_exclusivo))) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(label = num_contigs), position = position_dodge(width = 0.9), vjust = -0.5) +
  scale_fill_manual(values = c('brown3',"green4"), name = NULL) +
  labs(title = "Barplot of Unique vs Duplicate Contigs",
       x = "Chromosomes",
       y = "Number of Contigs") +
  theme_bw()

# Save cleaned dataset of exclusive contigs
classified <- filter(resumen, es_exclusivo == TRUE)
write_csv(classified, "clean_classified.csv")
